# Generated by Django 5.1.6 on 2025-03-25 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='dishes',
        ),
        migrations.AddField(
            model_name='order',
            name='eta',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
