# Generated by Django 5.1.7 on 2025-03-26 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_remove_restaurant_dishes_order_eta_alter_dish_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='food.order'),
        ),
    ]
