# Generated by Django 5.1.7 on 2025-04-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_dishorderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='bueno_external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='bueno_status',
            field=models.CharField(default='not_started', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='melange_external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='melange_status',
            field=models.CharField(default='not_started', max_length=30),
        ),
    ]
